### PR TITLE
crossfade sources

### PR DESCRIPTION
**Pull request by AJDurant**

### CODE REVIEW

**Comment by LordAro** [comment]
Rebased

**Comment by AJDurant** [comment]
Why did this need rebasing? There haven't been any changes?

**Comment by LordAro** [comment]
No idea, but there was a tabs vs indentation difference.

Is it otherwise still ready to go?

**Comment by AJDurant** [comment]
Yeah, it is obviously untested, and the timing may want to be slightly
different. It did try it out at the time locally and the function seemed
okay, but might not be exactly what is wanted.

**Pull request merged**
